apiVersion: "serving.kserve.io/v1alpha1"
kind: "InferenceService"
metadata:
  name: "my-inference-service"
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 2
    sklearn:
      storageUri: "s3://my-bucket/my-model"
      modelClassName: "MyModel"
      resources:
        limits:
          cpu: 1
          memory: 1Gi
